// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8V8upcyaiPnvpuLEuiBv_II5FvJ3mutY',
    appId: '1:252988213671:web:6c70f01b9ee07a158f8e82',
    messagingSenderId: '252988213671',
    projectId: 'cryptoquest-90a7b',
    authDomain: 'cryptoquest-90a7b.firebaseapp.com',
    storageBucket: 'cryptoquest-90a7b.firebasestorage.app',
    measurementId: 'G-J7CR8LY7CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH9Axyu_slFc4ZkCPhiPeqefdTw0zR_4g',
    appId: '1:252988213671:android:16fd85cb3e2b5e918f8e82',
    messagingSenderId: '252988213671',
    projectId: 'cryptoquest-90a7b',
    storageBucket: 'cryptoquest-90a7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBsBhw-oFMFGWcMEdjw3tr5RQppFXP10',
    appId: '1:252988213671:ios:0bf2213a7f51aa4e8f8e82',
    messagingSenderId: '252988213671',
    projectId: 'cryptoquest-90a7b',
    storageBucket: 'cryptoquest-90a7b.firebasestorage.app',
    iosBundleId: 'com.example.cryptoquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkBsBhw-oFMFGWcMEdjw3tr5RQppFXP10',
    appId: '1:252988213671:ios:0bf2213a7f51aa4e8f8e82',
    messagingSenderId: '252988213671',
    projectId: 'cryptoquest-90a7b',
    storageBucket: 'cryptoquest-90a7b.firebasestorage.app',
    iosBundleId: 'com.example.cryptoquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8V8upcyaiPnvpuLEuiBv_II5FvJ3mutY',
    appId: '1:252988213671:web:1aa5baf0733e0da38f8e82',
    messagingSenderId: '252988213671',
    projectId: 'cryptoquest-90a7b',
    authDomain: 'cryptoquest-90a7b.firebaseapp.com',
    storageBucket: 'cryptoquest-90a7b.firebasestorage.app',
    measurementId: 'G-S54BWZGZ5L',
  );
}
